### ISSUE TITLE
Make E2E tests more stable

### ISSUE THREAD

**Issue by bjaanes** [bjaanes/ExtremeResults-WebApp#46]
The e2e tests are failing from time to time right now. Both locally and on Travis. 

My initial guess is that it is related to the clearDB stuff. Perhaps we could wait for it to complete before starting each test file?

**Comment by bjaanes** [comment]
They seem stable locally now.

**Comment by bjaanes** [comment]
Error: socket hang up
    at createHangUpError (_http_client.js:200:15)
    at Socket.socketOnEnd (_http_client.js:292:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
